# Generated by Django 2.1.3 on 2018-11-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pizza', 'Pizza'), ('Topping', 'Topping'), ('Sub', 'Sub menu'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platters', 'Dinner Platters')], max_length=16)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
            ],
            options={
                'verbose_name': 'Dinner Platter',
                'verbose_name_plural': 'Dinner Platters',
            },
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('crust', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=8)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
                ('max_toppings', models.IntegerField(default=0)),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8)),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='toppings', to='orders.Topping'),
        ),
    ]
