# Generated by Django 2.1.3 on 2018-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping'),
        ),
    ]
