# Generated by Django 2.1.3 on 2018-11-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181128_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Topping', 'Topping'), ('Sub', 'Sub menu'), ('Extra', 'Extra'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platter', 'Dinner Platter')], max_length=16),
        ),
    ]
