# Generated by Django 2.1.3 on 2018-11-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='extra_cheese',
            new_name='extra',
        ),
    ]
