# Generated by Django 2.1.3 on 2018-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181128_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], max_length=8),
        ),
    ]
